export const cities = [
  {
    city: "Kuwait City",
    lat: "29.3697",
    lng: "47.9783",
    country: "Kuwait",
    iso2: "KW",
    admin_name: "Al ‘Āşimah",
    capital: "primary",
    population: "3000000",
    population_proper: "2989000",
  },
  {
    city: "Al Jahrā’",
    lat: "29.3500",
    lng: "47.6833",
    country: "Kuwait",
    iso2: "KW",
    admin_name: "Al Jahrā’",
    capital: "",
    population: "393432",
    population_proper: "393432",
  },
  {
    city: "Abū Ḩulayfah",
    lat: "29.1322",
    lng: "48.1261",
    country: "Kuwait",
    iso2: "KW",
    admin_name: "Al Aḩmadī",
    capital: "",
    population: "164212",
    population_proper: "164212",
  },
  {
    city: "Al Aḩmadī",
    lat: "29.0769",
    lng: "48.0838",
    country: "Kuwait",
    iso2: "KW",
    admin_name: "Al Aḩmadī",
    capital: "",
    population: "68763",
    population_proper: "68763",
  },
  {
    city: "Ar Riqqah",
    lat: "29.1489",
    lng: "48.1057",
    country: "Kuwait",
    iso2: "KW",
    admin_name: "Al Aḩmadī",
    capital: "",
    population: "56554",
    population_proper: "56554",
  },
  {
    city: "Al Bida‘",
    lat: "29.3025",
    lng: "48.0869",
    country: "Kuwait",
    iso2: "KW",
    admin_name: "Mubārak al Kabīr",
    capital: "",
    population: "",
    population_proper: "",
  },
  {
    city: "Al Farwānīyah",
    lat: "29.2770",
    lng: "47.9590",
    country: "Kuwait",
    iso2: "KW",
    admin_name: "Al Farwānīyah",
    capital: "",
    population: "",
    population_proper: "",
  },
  {
    city: "Abraq Khayţān",
    lat: "29.2925",
    lng: "47.9689",
    country: "Kuwait",
    iso2: "KW",
    admin_name: "Al Farwānīyah",
    capital: "",
    population: "",
    population_proper: "",
  },
  {
    city: "Al ‘Udaylīyah",
    lat: "29.3000",
    lng: "47.9667",
    country: "Kuwait",
    iso2: "KW",
    admin_name: "Al Farwānīyah",
    capital: "",
    population: "",
    population_proper: "",
  },
  {
    city: "Al ‘Abbāsīyah",
    lat: "29.2503",
    lng: "47.9311",
    country: "Kuwait",
    iso2: "KW",
    admin_name: "Al Farwānīyah",
    capital: "",
    population: "",
    population_proper: "",
  },
  {
    city: "Ash Shadādīyah",
    lat: "29.2681",
    lng: "47.8456",
    country: "Kuwait",
    iso2: "KW",
    admin_name: "Al Farwānīyah",
    capital: "",
    population: "",
    population_proper: "",
  },
  {
    city: "An Nijfah",
    lat: "29.2464",
    lng: "48.0758",
    country: "Kuwait",
    iso2: "KW",
    admin_name: "Mubārak al Kabīr",
    capital: "",
    population: "",
    population_proper: "",
  },
  {
    city: "Al Quşūr",
    lat: "29.2175",
    lng: "48.0726",
    country: "Kuwait",
    iso2: "KW",
    admin_name: "Mubārak al Kabīr",
    capital: "",
    population: "",
    population_proper: "",
  },
  {
    city: "Mishrif",
    lat: "29.2892",
    lng: "48.0500",
    country: "Kuwait",
    iso2: "KW",
    admin_name: "Mubārak al Kabīr",
    capital: "",
    population: "",
    population_proper: "",
  },
  {
    city: "Al Massīlah",
    lat: "29.2619",
    lng: "48.0797",
    country: "Kuwait",
    iso2: "KW",
    admin_name: "Mubārak al Kabīr",
    capital: "",
    population: "",
    population_proper: "",
  },
  {
    city: "Al Funayţīs",
    lat: "29.2253",
    lng: "48.1017",
    country: "Kuwait",
    iso2: "KW",
    admin_name: "Mubārak al Kabīr",
    capital: "",
    population: "",
    population_proper: "",
  },
  {
    city: "Al Maqwa‘",
    lat: "29.1667",
    lng: "47.9833",
    country: "Kuwait",
    iso2: "KW",
    admin_name: "Al Aḩmadī",
    capital: "",
    population: "",
    population_proper: "",
  },
  {
    city: "An Nuqayyāt",
    lat: "28.9431",
    lng: "48.1986",
    country: "Kuwait",
    iso2: "KW",
    admin_name: "Al Aḩmadī",
    capital: "",
    population: "",
    population_proper: "",
  },
  {
    city: "Duwaydāt",
    lat: "28.5828",
    lng: "48.3992",
    country: "Kuwait",
    iso2: "KW",
    admin_name: "Al Aḩmadī",
    capital: "",
    population: "",
    population_proper: "",
  },
  {
    city: "Aţ Ţawīl",
    lat: "28.9786",
    lng: "47.9072",
    country: "Kuwait",
    iso2: "KW",
    admin_name: "Al Aḩmadī",
    capital: "",
    population: "",
    population_proper: "",
  },
  {
    city: "Al Qurayn",
    lat: "29.2043",
    lng: "48.0757",
    country: "Kuwait",
    iso2: "KW",
    admin_name: "Al Aḩmadī",
    capital: "",
    population: "",
    population_proper: "",
  },
  {
    city: "Al ‘Uqaylah",
    lat: "29.1778",
    lng: "48.0947",
    country: "Kuwait",
    iso2: "KW",
    admin_name: "Al Aḩmadī",
    capital: "",
    population: "",
    population_proper: "",
  },
  {
    city: "Aḑ Ḑibā‘īyah",
    lat: "28.9333",
    lng: "48.1667",
    country: "Kuwait",
    iso2: "KW",
    admin_name: "Al Aḩmadī",
    capital: "",
    population: "",
    population_proper: "",
  },
  {
    city: "‘Urayfijān",
    lat: "28.9000",
    lng: "48.1833",
    country: "Kuwait",
    iso2: "KW",
    admin_name: "Al Aḩmadī",
    capital: "",
    population: "",
    population_proper: "",
  },
  {
    city: "Ash Shu‘aybah",
    lat: "28.9592",
    lng: "48.1345",
    country: "Kuwait",
    iso2: "KW",
    admin_name: "Al Aḩmadī",
    capital: "",
    population: "",
    population_proper: "",
  },
  {
    city: "Az Zawr",
    lat: "28.7375",
    lng: "48.3728",
    country: "Kuwait",
    iso2: "KW",
    admin_name: "Al Aḩmadī",
    capital: "",
    population: "",
    population_proper: "",
  },
  {
    city: "Umm Qaşbah",
    lat: "28.9922",
    lng: "48.1656",
    country: "Kuwait",
    iso2: "KW",
    admin_name: "Al Aḩmadī",
    capital: "",
    population: "",
    population_proper: "",
  },
  {
    city: "Aş Şabāḩīyah",
    lat: "29.1058",
    lng: "48.1081",
    country: "Kuwait",
    iso2: "KW",
    admin_name: "Al Aḩmadī",
    capital: "",
    population: "",
    population_proper: "",
  },
  {
    city: "Al Qulay‘ah",
    lat: "28.8658",
    lng: "48.2747",
    country: "Kuwait",
    iso2: "KW",
    admin_name: "Al Aḩmadī",
    capital: "",
    population: "",
    population_proper: "",
  },
  {
    city: "Manīfah",
    lat: "29.1608",
    lng: "48.0811",
    country: "Kuwait",
    iso2: "KW",
    admin_name: "Al Aḩmadī",
    capital: "",
    population: "",
    population_proper: "",
  },
  {
    city: "Al Manqaf",
    lat: "29.0961",
    lng: "48.1328",
    country: "Kuwait",
    iso2: "KW",
    admin_name: "Al Aḩmadī",
    capital: "",
    population: "",
    population_proper: "",
  },
  {
    city: "Mubārak al Kabīr",
    lat: "29.1898",
    lng: "48.0872",
    country: "Kuwait",
    iso2: "KW",
    admin_name: "Al Aḩmadī",
    capital: "",
    population: "",
    population_proper: "",
  },
  {
    city: "Şubayḩīyah",
    lat: "28.8794",
    lng: "47.9139",
    country: "Kuwait",
    iso2: "KW",
    admin_name: "Al Aḩmadī",
    capital: "",
    population: "",
    population_proper: "",
  },
  {
    city: "Ju‘aydān",
    lat: "28.9667",
    lng: "47.9672",
    country: "Kuwait",
    iso2: "KW",
    admin_name: "Al Aḩmadī",
    capital: "",
    population: "",
    population_proper: "",
  },
];
